# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connect_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddServer(object):
    def setupUi(self, AddServer):
        AddServer.setObjectName("AddServer")
        AddServer.resize(400, 189)
        AddServer.setMinimumSize(QtCore.QSize(400, 189))
        AddServer.setMaximumSize(QtCore.QSize(400, 189))
        self.verticalLayout = QtWidgets.QVBoxLayout(AddServer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.server_layout = QtWidgets.QHBoxLayout()
        self.server_layout.setObjectName("server_layout")
        self.label = QtWidgets.QLabel(AddServer)
        self.label.setObjectName("label")
        self.server_layout.addWidget(self.label)
        self.server_ip = QtWidgets.QLineEdit(AddServer)
        self.server_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.server_ip.setObjectName("server_ip")
        self.server_layout.addWidget(self.server_ip)
        self.server_port = QtWidgets.QSpinBox(AddServer)
        self.server_port.setAlignment(QtCore.Qt.AlignCenter)
        self.server_port.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.server_port.setMaximum(65535)
        self.server_port.setObjectName("server_port")
        self.server_layout.addWidget(self.server_port)
        self.verticalLayout.addLayout(self.server_layout)
        self.userdata_box = QtWidgets.QGroupBox(AddServer)
        self.userdata_box.setObjectName("userdata_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.userdata_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_1 = QtWidgets.QLabel(self.userdata_box)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout.addWidget(self.label_1)
        self.nickname = QtWidgets.QLineEdit(self.userdata_box)
        self.nickname.setAlignment(QtCore.Qt.AlignCenter)
        self.nickname.setObjectName("nickname")
        self.horizontalLayout.addWidget(self.nickname)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.userdata_box)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(self.userdata_box)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.horizontalLayout_2.addWidget(self.password)
        self.label_4 = QtWidgets.QLabel(self.userdata_box)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.confirm = QtWidgets.QLineEdit(self.userdata_box)
        self.confirm.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.confirm.setObjectName("confirm")
        self.horizontalLayout_2.addWidget(self.confirm)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.userdata_box)
        self.buttons_layout = QtWidgets.QHBoxLayout()
        self.buttons_layout.setObjectName("buttons_layout")
        self.new_tab_btn = QtWidgets.QPushButton(AddServer)
        self.new_tab_btn.setObjectName("new_tab_btn")
        self.buttons_layout.addWidget(self.new_tab_btn)
        self.connect_btn = QtWidgets.QPushButton(AddServer)
        self.connect_btn.setObjectName("connect_btn")
        self.buttons_layout.addWidget(self.connect_btn)
        self.cancel_btn = QtWidgets.QPushButton(AddServer)
        self.cancel_btn.setObjectName("cancel_btn")
        self.buttons_layout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.buttons_layout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 4)

        self.retranslateUi(AddServer)
        QtCore.QMetaObject.connectSlotsByName(AddServer)

    def retranslateUi(self, AddServer):
        _translate = QtCore.QCoreApplication.translate
        AddServer.setWindowTitle(_translate("AddServer", "Connect"))
        self.label.setText(_translate("AddServer", "Server Address: "))
        self.userdata_box.setTitle(_translate("AddServer", "Userdata"))
        self.label_1.setText(_translate("AddServer", "Nickname"))
        self.label_3.setText(_translate("AddServer", "Password"))
        self.label_4.setText(_translate("AddServer", "Confirm"))
        self.new_tab_btn.setText(_translate("AddServer", "In new tab"))
        self.connect_btn.setText(_translate("AddServer", "Connect"))
        self.cancel_btn.setText(_translate("AddServer", "Cancel"))

