# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Messager(object):
    def setupUi(self, Messager):
        Messager.setObjectName("Messager")
        Messager.resize(600, 400)
        Messager.setMinimumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(Messager)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.room_list = QtWidgets.QListWidget(self.centralwidget)
        self.room_list.setObjectName("room_list")
        self.horizontalLayout.addWidget(self.room_list)
        self.chat_layout = QtWidgets.QVBoxLayout()
        self.chat_layout.setSpacing(1)
        self.chat_layout.setObjectName("chat_layout")
        self.chat_list = QtWidgets.QListWidget(self.centralwidget)
        self.chat_list.setObjectName("chat_list")
        self.chat_layout.addWidget(self.chat_list)
        self.messag_area = QtWidgets.QHBoxLayout()
        self.messag_area.setObjectName("messag_area")
        self.message_box = QtWidgets.QLineEdit(self.centralwidget)
        self.message_box.setObjectName("message_box")
        self.messag_area.addWidget(self.message_box)
        self.send_message = QtWidgets.QPushButton(self.centralwidget)
        self.send_message.setObjectName("send_message")
        self.messag_area.addWidget(self.send_message)
        self.chat_layout.addLayout(self.messag_area)
        self.horizontalLayout.addLayout(self.chat_layout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        Messager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Messager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuConnections = QtWidgets.QMenu(self.menubar)
        self.menuConnections.setObjectName("menuConnections")
        self.menuSelf = QtWidgets.QMenu(self.menubar)
        self.menuSelf.setObjectName("menuSelf")
        self.menuPermissions = QtWidgets.QMenu(self.menubar)
        self.menuPermissions.setObjectName("menuPermissions")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Messager.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Messager)
        self.statusbar.setObjectName("statusbar")
        Messager.setStatusBar(self.statusbar)
        self.actionConnect = QtWidgets.QAction(Messager)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect_from_current = QtWidgets.QAction(Messager)
        self.actionDisconnect_from_current.setObjectName("actionDisconnect_from_current")
        self.actionServer_list = QtWidgets.QAction(Messager)
        self.actionServer_list.setObjectName("actionServer_list")
        self.actionChange_password = QtWidgets.QAction(Messager)
        self.actionChange_password.setObjectName("actionChange_password")
        self.actionChange_nickname = QtWidgets.QAction(Messager)
        self.actionChange_nickname.setObjectName("actionChange_nickname")
        self.actionChange_username = QtWidgets.QAction(Messager)
        self.actionChange_username.setObjectName("actionChange_username")
        self.actionChange_proxy = QtWidgets.QAction(Messager)
        self.actionChange_proxy.setObjectName("actionChange_proxy")
        self.actionChange_username_2 = QtWidgets.QAction(Messager)
        self.actionChange_username_2.setObjectName("actionChange_username_2")
        self.actionDisconnect = QtWidgets.QAction(Messager)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.menuConnections.addAction(self.actionConnect)
        self.menuConnections.addAction(self.actionDisconnect_from_current)
        self.menuConnections.addAction(self.actionServer_list)
        self.menuSelf.addAction(self.actionChange_password)
        self.menuSelf.addAction(self.actionChange_nickname)
        self.menuSelf.addAction(self.actionChange_username)
        self.menuTools.addAction(self.actionChange_proxy)
        self.menuTools.addAction(self.actionChange_username_2)
        self.menubar.addAction(self.menuConnections.menuAction())
        self.menubar.addAction(self.menuSelf.menuAction())
        self.menubar.addAction(self.menuPermissions.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Messager)
        QtCore.QMetaObject.connectSlotsByName(Messager)

    def retranslateUi(self, Messager):
        _translate = QtCore.QCoreApplication.translate
        Messager.setWindowTitle(_translate("Messager", "Postogramm"))
        self.send_message.setText(_translate("Messager", "Send"))
        self.menuConnections.setTitle(_translate("Messager", "Connections"))
        self.menuSelf.setTitle(_translate("Messager", "Self"))
        self.menuPermissions.setTitle(_translate("Messager", "Permissions"))
        self.menuTools.setTitle(_translate("Messager", "Tools"))
        self.menuHelp.setTitle(_translate("Messager", "Help"))
        self.actionConnect.setText(_translate("Messager", "Connect"))
        self.actionDisconnect_from_current.setText(_translate("Messager", "Disconnect from current"))
        self.actionServer_list.setText(_translate("Messager", "Server list"))
        self.actionChange_password.setText(_translate("Messager", "Change password"))
        self.actionChange_nickname.setText(_translate("Messager", "Change nickname"))
        self.actionChange_username.setText(_translate("Messager", "Change username"))
        self.actionChange_proxy.setText(_translate("Messager", "Change proxy"))
        self.actionChange_username_2.setText(_translate("Messager", "Change username"))
        self.actionDisconnect.setText(_translate("Messager", "Disconnect"))

