# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Messager(object):
    def setupUi(self, Messager):
        Messager.setObjectName("Messager")
        Messager.resize(795, 601)
        Messager.setMinimumSize(QtCore.QSize(795, 601))
        self.centralwidget = QtWidgets.QWidget(Messager)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.find_sb_layout = QtWidgets.QHBoxLayout()
        self.find_sb_layout.setObjectName("find_sb_layout")
        self.open_sb_btn = QtWidgets.QToolButton(self.centralwidget)
        self.open_sb_btn.setText("")
        self.open_sb_btn.setObjectName("open_sb_btn")
        self.find_sb_layout.addWidget(self.open_sb_btn)
        self.search_t = QtWidgets.QLineEdit(self.centralwidget)
        self.search_t.setObjectName("search_t")
        self.find_sb_layout.addWidget(self.search_t)
        self.verticalLayout.addLayout(self.find_sb_layout)
        self.room_list = QtWidgets.QListWidget(self.centralwidget)
        self.room_list.setObjectName("room_list")
        self.verticalLayout.addWidget(self.room_list)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 11)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.messaging_layout = QtWidgets.QWidget(self.centralwidget)
        self.messaging_layout.setEnabled(True)
        self.messaging_layout.setAcceptDrops(False)
        self.messaging_layout.setObjectName("messaging_layout")
        self.chat_layout = QtWidgets.QVBoxLayout(self.messaging_layout)
        self.chat_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.chat_layout.setSpacing(0)
        self.chat_layout.setObjectName("chat_layout")
        self.chat_info_layout = QtWidgets.QHBoxLayout()
        self.chat_info_layout.setObjectName("chat_info_layout")
        self.n_a_u_layout = QtWidgets.QVBoxLayout()
        self.n_a_u_layout.setObjectName("n_a_u_layout")
        self.chat_name_l = QtWidgets.QLabel(self.messaging_layout)
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chat_name_l.setFont(font)
        self.chat_name_l.setTextFormat(QtCore.Qt.AutoText)
        self.chat_name_l.setScaledContents(False)
        self.chat_name_l.setObjectName("chat_name_l")
        self.n_a_u_layout.addWidget(self.chat_name_l)
        self.chat_members_l = QtWidgets.QLabel(self.messaging_layout)
        self.chat_members_l.setObjectName("chat_members_l")
        self.n_a_u_layout.addWidget(self.chat_members_l)
        self.chat_info_layout.addLayout(self.n_a_u_layout)
        self.chat_search_btn = QtWidgets.QToolButton(self.messaging_layout)
        self.chat_search_btn.setObjectName("chat_search_btn")
        self.chat_info_layout.addWidget(self.chat_search_btn)
        self.chat_info_btn = QtWidgets.QToolButton(self.messaging_layout)
        self.chat_info_btn.setObjectName("chat_info_btn")
        self.chat_info_layout.addWidget(self.chat_info_btn)
        self.chat_menu_btn = QtWidgets.QToolButton(self.messaging_layout)
        self.chat_menu_btn.setObjectName("chat_menu_btn")
        self.chat_info_layout.addWidget(self.chat_menu_btn)
        self.chat_layout.addLayout(self.chat_info_layout)
        self.chat_list = QtWidgets.QListWidget(self.messaging_layout)
        self.chat_list.setObjectName("chat_list")
        self.chat_layout.addWidget(self.chat_list)
        self.messag_area = QtWidgets.QHBoxLayout()
        self.messag_area.setObjectName("messag_area")
        self.message_box = QtWidgets.QLineEdit(self.messaging_layout)
        self.message_box.setObjectName("message_box")
        self.messag_area.addWidget(self.message_box)
        self.send_message = QtWidgets.QToolButton(self.messaging_layout)
        self.send_message.setObjectName("send_message")
        self.messag_area.addWidget(self.send_message)
        self.chat_layout.addLayout(self.messag_area)
        self.horizontalLayout.addWidget(self.messaging_layout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        Messager.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Messager)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 30))
        self.menubar.setObjectName("menubar")
        self.menuConnections = QtWidgets.QMenu(self.menubar)
        self.menuConnections.setObjectName("menuConnections")
        self.menuSelf = QtWidgets.QMenu(self.menubar)
        self.menuSelf.setObjectName("menuSelf")
        self.menuPermissions = QtWidgets.QMenu(self.menubar)
        self.menuPermissions.setObjectName("menuPermissions")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Messager.setMenuBar(self.menubar)
        self.actionConnect = QtWidgets.QAction(Messager)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect_from_current = QtWidgets.QAction(Messager)
        self.actionDisconnect_from_current.setObjectName("actionDisconnect_from_current")
        self.actionServer_list = QtWidgets.QAction(Messager)
        self.actionServer_list.setObjectName("actionServer_list")
        self.actionChange_password = QtWidgets.QAction(Messager)
        self.actionChange_password.setObjectName("actionChange_password")
        self.actionChange_nickname = QtWidgets.QAction(Messager)
        self.actionChange_nickname.setObjectName("actionChange_nickname")
        self.actionChange_username = QtWidgets.QAction(Messager)
        self.actionChange_username.setObjectName("actionChange_username")
        self.actionChange_proxy = QtWidgets.QAction(Messager)
        self.actionChange_proxy.setObjectName("actionChange_proxy")
        self.actionChange_username_2 = QtWidgets.QAction(Messager)
        self.actionChange_username_2.setObjectName("actionChange_username_2")
        self.actionDisconnect = QtWidgets.QAction(Messager)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.menuConnections.addAction(self.actionConnect)
        self.menuConnections.addAction(self.actionDisconnect_from_current)
        self.menuConnections.addAction(self.actionServer_list)
        self.menuSelf.addAction(self.actionChange_password)
        self.menuSelf.addAction(self.actionChange_nickname)
        self.menuSelf.addAction(self.actionChange_username)
        self.menuTools.addAction(self.actionChange_proxy)
        self.menuTools.addAction(self.actionChange_username_2)
        self.menubar.addAction(self.menuConnections.menuAction())
        self.menubar.addAction(self.menuSelf.menuAction())
        self.menubar.addAction(self.menuPermissions.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Messager)
        QtCore.QMetaObject.connectSlotsByName(Messager)

    def retranslateUi(self, Messager):
        _translate = QtCore.QCoreApplication.translate
        Messager.setWindowTitle(_translate("Messager", "Postogramm"))
        self.chat_name_l.setText(_translate("Messager", "Chat &Name"))
        self.chat_members_l.setText(_translate("Messager", "Chat &Members"))
        self.chat_search_btn.setText(_translate("Messager", "..."))
        self.chat_info_btn.setText(_translate("Messager", "..."))
        self.chat_menu_btn.setText(_translate("Messager", "..."))
        self.send_message.setText(_translate("Messager", ">"))
        self.menuConnections.setTitle(_translate("Messager", "&Connections"))
        self.menuSelf.setTitle(_translate("Messager", "&Self"))
        self.menuPermissions.setTitle(_translate("Messager", "&Permissions"))
        self.menuTools.setTitle(_translate("Messager", "&Tools"))
        self.menuHelp.setTitle(_translate("Messager", "&Help"))
        self.actionConnect.setText(_translate("Messager", "&Connect"))
        self.actionDisconnect_from_current.setText(_translate("Messager", "&Disconnect from current"))
        self.actionServer_list.setText(_translate("Messager", "&Server list"))
        self.actionChange_password.setText(_translate("Messager", "&Change password"))
        self.actionChange_nickname.setText(_translate("Messager", "Change &nickname"))
        self.actionChange_username.setText(_translate("Messager", "Change &username"))
        self.actionChange_proxy.setText(_translate("Messager", "&Change proxy"))
        self.actionChange_username_2.setText(_translate("Messager", "Change &username"))
        self.actionDisconnect.setText(_translate("Messager", "Disconnect"))
